//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETSirketOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirket
    {
        public int ID { get; set; }
        public string SirketAdi { get; set; }
        public string Tel_1 { get; set; }
        public string Tel_2 { get; set; }
        public string Fax { get; set; }
        public string Emil { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> KurulusTarihi { get; set; }
    }
}
