//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETSirketOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkilendirme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yetkilendirme()
        {
            this.Kullanicilars = new HashSet<Kullanicilar>();
        }
    
        public int ID { get; set; }
        public string Yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        public virtual Yetkilendirme Yetkilendirme1 { get; set; }
        public virtual Yetkilendirme Yetkilendirme2 { get; set; }
    }
}
